### PR TITLE
Bugfix: negative epochs crash

### LINKED ISSUE #2: rizzy -n doesn't handle large negative value
```
% echo '-9223372036854775808' | rizzy -n
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow }', src/rizzy.rs:77:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
% echo '-9223372036854775807' | rizzy -n
-2262-04-11T17:47:16.854775807-06:00
% rizzy --version
rizzy 0.1.1
```

### PR DESCRIPTION
**Pull request by siedentop**
- Fix 1: A parsing error means we just keep the original number around.

(This is just a suggestion, and the maintainers might prefer an alternative solution.)

- Fix 2: Use signed 64 big to get a tiny bit more range.

Since the regex is looking for 19 digits only, this will fix the issue,
as 2^63 has 19 digits but 2^64 has 20 digits. Thus with the range up
to 2^64, we're in the clear.

----

EDIT: The above was auto-generated with the Github CLI.

Question to @mattgodbolt (and maintainers): What is the behavior you'd like to see?

Fixes: https://github.com/aquanauts/rizzy/issues/2

### CODE REVIEW

**Comment by mattgodbolt** [comment]
I think ideally we'd ignore it and "just" print the ASCII unadorned (much as if it wasn't actually a timestamp at all) - is that easy to change? Sorry for causing a conflct (with yourself!) in the merge too!

**Comment by siedentop** [comment]
@mattgodbolt I just reverted to the first commit, which would just keep the original text if it failed to parse as a number. Is this what you meant?

BTW: Which style do you prefer?

"Functional" using `map()` and `unwrap_or`: 

```Rust
            replaced = NS_RE
                .replace_all(&replaced, |caps: &Captures<'_>| {
                    let m = caps.get(0).unwrap().as_str();
                    let s: String = m
                        .parse::<i64>()
                        .map(|ts| {
                            let utc_time = NaiveDateTime::from_timestamp(
                                ts / 1_000_000_000,
                                (ts % 1_000_000_000) as u32,
                            );
                            self.format_time(&utc_time)
                        })
                        .unwrap_or(m.to_string());
                    s
                })
                .to_string();
```

"Procedural" using a `match` block:

```Rust
           replaced = NS_RE
                 .replace_all(&replaced, |caps: &Captures<'_>| {
                     match caps.get(0).unwrap().as_str().parse::<i64>() {
                         Ok(ts) => {
                             let utc_time = NaiveDateTime::from_timestamp(
                                 ts / 1_000_000_000,
                                 (ts % 1_000_000_000) as u32,
                             );
                             self.format_time(&utc_time)
                         }
                         // On parsing error (if match is too big for i64), keep the original string.
                         Err(_e) => caps.get(0).unwrap().as_str().to_string(),
                     }
                 })
                 .to_string();
```

**Comment by mattgodbolt** [comment]
> keep original text if it failed.

Yup! that I think is great!

> style questions

I'm actually not sure, both have merit...so ! Whichever you think is best :)

**Review by mattgodbolt — APPROVED** [review]
I'll hold off merging in case you want to change to the other style. But let me know! Thank you!

**Comment by mattgodbolt** [comment]
(will merge later today if I don't hear back -- we can always change the code if you have further thoughts)

**Comment by siedentop** [comment]
Thanks! 

I'd prefer the current version (using a `match` block). 

I think it reads slightly better, and the functional doesn't add any benefit (in this case).

**Comment by mattgodbolt** [comment]
Awesome! Thanks so much!

**Pull request merged**
