### PR TITLE
Support reading from files on the command-line

### PR DESCRIPTION
**Pull request by mattgodbolt**
Not just from `stdin`.

I'd love more ideas as how to de-duplicate the code, and also if there's a nice way to support `-` being an argument.

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Also CC @siedentop who probably can review my awful code a lot more closely :)

**Comment by siedentop** [comment]
Thanks, Matt, for asking for feedback!

First of all, I think this could be merged as is. I have two areas of improvement, but I can totally see that maybe those changes might be out of scope.

1. Personally, I am a fan of *eyre* and *color-eyre* for error handling. For files specifically, you'd want to add error.context(<filename>), so you know which file failed to open. To me this is cleaner than using `panic!`. The end result should be the same, though. I'll provide example code below. (As a guess, binary size will increase slightly, runtime will stay the same, and startup time might increase a tiny bit.)
2. Secondly, the way you distinguish between file and stdin reading is fine to me. But it could be done differently. I am, however, by no means an expert on that. Both stdin and File implemented the *Read* trait, and you could have a `dyn Read` over which you later iterate. The link below gives a nice example. However, the way you're currently doing it, is totally fine. 

Good read: https://phrohdoh.com/blog/read-from-file-or-stdin-rust/
Potentially useful (although I don't see the need): https://docs.rs/clio/latest/clio/

I know I promised code, but I have to go to dinner.

```rust
// NOTE: you need to add eyre and color_eyre to Cargo.
fn main() -> eyre::Result<()> {
    let opts: Opts = Opts::parse();
    color_eyre::install()?;
    let rizzy = Rizzy::new(get_timezone(&opts), opts.format, opts.convert_epoch_nanos);

    if opts.file.is_empty() {
        for line in io::stdin().lock().lines() {
            println!("{}", rizzy.handle_line(&line.unwrap()));
        }
    } else {
        for file in opts.file {
            let lines =
                read_lines(&file).with_context(|| format!("Failed to open file '{}'", file))?;
            // BTW: Did you know that since Rust 1.58 you can write `format!("Bla blub {file}")`
            for line in lines {
                println!("{}", rizzy.handle_line(&line.unwrap()));
            }
        }
    }
    Ok(())
}
```

**Comment by mattgodbolt** [comment]
Thanks @siedentop . The `eyre` thing is much nicer and I think is more appropriate as a change to close #9. Thanks for the links!

**Review by apmorton — APPROVED** [review]
LGTM, but I am sight-reading here as I don't really know rust

**Comment by mattgodbolt** [comment]
Thanks @apmorton - just really a second pair of eyes (in addition to @siedentop 's thoughts!)

**Pull request merged**
